### ISSUE TITLE
Is the 1.9.4 JAR lib compatible with JDK 1.8 ?

### ISSUE THREAD

**Issue by EmbGangsta** [makbn/java_leaflet#26]
I am trying to use your JLMAP .jar library as is without recompilation from the JAR files I got from the github page

I use netbeans IDE and compiling with JDK 1.8 and I get the infamous error at runtime : 

warning: [options] bootstrap class path not set in conjunction with -source 1.7
D:\TestMapsInJavaFXPanel\src\testmapsinjavafxpanel\NewClass.java:8: error: cannot access JLMapView
import io.github.makbn.jlmap.JLMapView;
  bad class file: D:\TestMapsInJavaFXPanel\lib\jlmap-1.9.4-jar-with-dependencies.jar(io/github/makbn/jlmap/JLMapView.class)
    class file has wrong version 61.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
BUILD FAILED (total time: 0 seconds)

It seems your Jar need JDK 1.7 isnt it ?

**Comment by makbn** [comment]
Hi @EmbGangsta, I'll look into this issue this weekend and will post an update here! thanks for sharing it.

**Comment by makbn** [comment]
you need JDK +11 to run the current version of the project
